#!/usr/bin/env bash
# This script will be used to spin up the development servers for all the {{cookiecutter.project_name}} applications

# change to the project folder
cd "$HOME/{{cookiecutter.project_name}}"

# directory path of django development server
backend_folder="{{cookiecutter.django_project_name}}"
# directory path of nuxt development server
frontend_folder="{{cookiecutter.nuxt_project_name}}"
# directory path of documentation development server
documentation_folder="{{cookiecutter.docs_project_name}}"

# Start all the servers
{ cd "$backend_folder" && poetry run python3 manage.py runserver_plus 0.0.0.0:8000 & \
  cd "$frontend_folder" && yarn dev; }
# { cd "$backend_folder" && poetry run python3 manage.py runserver_plus 0.0.0.0:8000 & \
#   cd "$frontend_folder" && yarn dev & \
#   cd "$documentation_folder" && yarn start; }
