#!/usr/bin/env bash
# This script will be used to spin up the development servers for all the {{cookiecutter.project_name}} applications

# change to the project folder
cd "$HOME/{{cookiecutter.project_name}}"
yarn dev
