#!/usr/bin/env bash
# This script will be used to spin up the development servers for all the {{cookiecutter.project_name}} applications

# change to the project folder
cd "/home/vagrant/{{cookiecutter.project_name}}"

# directory path of nuxt development server
frontend_folder="{{cookiecutter.nuxt_project_name}}"

# Start all the servers
cd "$frontend_folder" && yarn dev
