#!/usr/bin/env bash

set -e
set -x

# Install dependencies for Django backend
cd /home/vagrant/{{cookiecutter.project_name}}/{{cookiecutter.django_project_name}}
pip3 install -r requirements.txt

# Install dependencies for Nuxt frontend
cd /home/vagrant/{{cookiecutter.project_name}}/{{cookiecutter.nuxt_project_name}}-frontend
yarn install

# Install dependencies for Docusaurus documentation
cd /home/vagrant/{{cookiecutter.project_name}}/{{cookiecutter.docs_project_name}}-docs/website
yarn install
