#!/usr/bin/env bash
# This script will be used to spin up the development servers for all the {{cookiecutter.project_name}} applications

# change to the project folder
cd "$HOME/{{cookiecutter.project_name}}"


# Start all the servers
poetry run python3 manage.py runserver_plus 0.0.0.0:8000

