#!/usr/bin/env bash
# This script will be used to spin up the development servers for all the {{cookiecutter.project_name}} applications

# Start the django development server
cd /home/vagrant/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}
python3 manage.py runserver 0.0.0.0:8000 > /home/vagrant/{{cookiecutter.project_name}}/.vagrant/{{cookiecutter.project_name}}-backend.log 2>&1 &
echo $! > /home/vagrant/{{cookiecutter.project_name}}/.vagrant/{{cookiecutter.project_name}}-backend.pid
printf "Started django development server!\n\n"

# Start the nuxtjs development server
cd /home/vagrant/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}-frontend
npm run dev > /home/vagrant/{{cookiecutter.project_name}}/.vagrant/{{cookiecutter.project_name}}-frontend.log 2>&1 &
echo $! > /home/vagrant/{{cookiecutter.project_name}}/.vagrant/{{cookiecutter.project_name}}-frontend.pid
printf "Started nuxtjs development server!\n\n"

# Start the documentation development server
# cd /home/vagrant/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}-docs/website
# npm run start > /home/vagrant/{{cookiecutter.project_name}}/.vagrant/{{cookiecutter.project_name}}-docs.log 2>&1 &
# echo $! > /home/vagrant/{{cookiecutter.project_name}}/.vagrant/{{cookiecutter.project_name}}-docs.pid
# printf "Started documentation development server!\n\n"
