#!/usr/bin/env bash
# This script will be used to spin up the development servers for all the {{cookiecutter.project_name}} applications

# Start the django development server
cd /home/vagrant/{{cookiecutter.project_name}}/{{cookiecutter.django_project_name}}
python3 manage.py runserver 0.0.0.0:8000 > /home/vagrant/{{cookiecutter.project_name}}/.vagrant/{{cookiecutter.django_project_name}}-backend.log 2>&1 &
echo $! > /home/vagrant/{{cookiecutter.project_name}}/.vagrant/{{cookiecutter.django_project_name}}-backend.pid
printf "Started django development server!\n\n"

# Start the nuxtjs development server
cd /home/vagrant/{{cookiecutter.project_name}}/{{cookiecutter.nuxt_project_name}}
yarn dev > /home/vagrant/{{cookiecutter.project_name}}/.vagrant/{{cookiecutter.nuxt_project_name}}.log 2>&1 &
echo $! > /home/vagrant/{{cookiecutter.project_name}}/.vagrant/{{cookiecutter.nuxt_project_name}}.pid
printf "Started nuxtjs development server!\n\n"

# Start the documentation development server
cd /home/vagrant/{{cookiecutter.project_name}}/{{cookiecutter.docs_project_name}}/website
yarn start > /home/vagrant/{{cookiecutter.project_name}}/.vagrant/{{cookiecutter.docs_project_name}}.log 2>&1 &
echo $! > /home/vagrant/{{cookiecutter.project_name}}/.vagrant/{{cookiecutter.docs_project_name}}.pid
printf "Started documentation development server!\n\n"
