#!/usr/bin/env bash
# This script will be used to stop the development servers spawned by `tools/run-dev`

# Kill the django development server
fuser -k 8000/tcp
printf "Stopped django development server!\n\n"

# Kill the nuxtjs development server
fuser -k 3000/tcp
printf "Stopped nuxtjs development server!\n\n"

# Kill the documentation development server
# fuser -k 8080/tcp
# printf "Stopped documentation development server!\n"
