# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.host_name = "{{cookiecutter.project_name|lower|replace(' ', '-')}}-development"
  config.vm.network "forwarded_port", guest: 8000, host: 8000, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 3000, host: 3000, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
  config.vm.synced_folder ".", "/home/vagrant/{{cookiecutter.project_name}}"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3072"
    vb.cpus = "2"
  end
  config.vm.provision :shell, :path => "tools/Vagrant/bootstrap"
  config.vm.provision :shell, :path => "tools/Vagrant/setup-deps"
  config.vm.provision :shell, :path => "tools/shell/env-vars"
end
