#!/usr/bin/env bash
# Based on script from https://github.com/jackdb/pg-app-dev-vm/blob/master/Vagrant-setup/bootstrap.sh

set -e

function coloredEcho(){
  # taken from https://stackoverflow.com/a/23006365/11667450
    local exp=$1;
    local color=$2;
    if ! [[ $color =~ '^[0-9]$' ]] ; then
       case $(echo $color | tr '[:upper:]' '[:lower:]') in
        black) color=0 ;;
        red) color=1 ;; # error
        green) color=2 ;; # success
        yellow) color=3 ;; # warning
        blue) color=4 ;; # completion
        magenta) color=5 ;;
        cyan) color=6 ;; # info
        white|*) color=7 ;; # white or invalid color
       esac
    fi
    tput setaf $color;
    echo $exp;
    tput sgr0;
}

coloredEcho "Setting configuration variables" "cyan"

# Edit the following to change the name of the database user that will be created:
APP_DB_USER="{{cookiecutter.postgres_admin_user}}"
APP_DB_PASS="{{cookiecutter.postgres_password}}"

# Edit the following to change the name of the database that is created (defaults to the user name)
APP_DB_NAME="{{cookiecutter.postgres_database_name}}"

# Edit the following to change the version of PostgreSQL that is installed
PG_VERSION=13

coloredEcho "Configuration variables complete" "cyan"

###########################################################
# Changes below this line are probably not necessary
###########################################################
print_db_usage () {
  coloredEcho "Admin access to postgres user via VM:" "green"
  coloredEcho "  vagrant ssh" "green"
  coloredEcho "  sudo su - postgres" "green"
  echo ""
  coloredEcho "psql access to app database user via VM:" "green"
  coloredEcho "  vagrant ssh" "green"
  coloredEcho "  sudo su - postgres" "green"
  coloredEcho "  PGUSER=$APP_DB_USER PGPASSWORD=$APP_DB_PASS psql -h localhost $APP_DB_NAME" "green"
}

export DEBIAN_FRONTEND=noninteractive

PROVISIONED_ON=/etc/vm_provision_on_timestamp
if [ -f "$PROVISIONED_ON" ]
then
  echo "VM was already provisioned at: $(cat $PROVISIONED_ON)"
  echo "To run system updates manually login via 'vagrant ssh' and run 'apt-get update && apt-get upgrade'"
  echo ""
  print_db_usage
  exit
fi

coloredEcho "Adding apt-keys and installing environment packages" "cyan"

PG_REPO_APT_SOURCE=/etc/apt/sources.list.d/pgdg.list
if [ ! -f "$PG_REPO_APT_SOURCE" ]
then
  # Add PG apt repo:
  echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > "$PG_REPO_APT_SOURCE"
  # Add PGDG repo key:
  wget --quiet -O - https://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | apt-key add -
fi

# Get installer for nodejs
curl -sL https://deb.nodesource.com/setup_15.x | bash -
# get installer for yarn
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
# Update package list
apt-get update

# Install postgresql, python3.9 and fish shell (required for development)
apt-get -y install "yarn" "postgresql-$PG_VERSION" "postgresql-contrib-$PG_VERSION" "fish" "python3" "python3-pip" "nodejs" "gcc" "g++" "make"

coloredEcho "Environment packages installed successfully!" "yellow"

PG_CONF="/etc/postgresql/$PG_VERSION/main/postgresql.conf"
PG_HBA="/etc/postgresql/$PG_VERSION/main/pg_hba.conf"
PG_DIR="/var/lib/postgresql/$PG_VERSION/main"

# Edit postgresql.conf to change listen address to '*':
sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" "$PG_CONF"

# Append to pg_hba.conf to add password auth:
echo "host    all             all             all                     md5" >> "$PG_HBA"

# Explicitly set default client_encoding
echo "client_encoding = utf8" >> "$PG_CONF"

# Restart so that all new config is loaded:
service postgresql restart

coloredEcho "Creating database with the given parameters" "cyan"

cat << EOF | su - postgres -c psql
-- Create the database user:
CREATE ROLE "$APP_DB_USER" WITH LOGIN CREATEDB ENCRYPTED PASSWORD '$APP_DB_PASS';
-- Create the database:
CREATE DATABASE "$APP_DB_NAME" WITH OWNER="$APP_DB_USER"
                                  LC_COLLATE="en_US.utf8"
                                  LC_CTYPE="en_US.utf8"
                                  ENCODING="UTF8"
                                  TEMPLATE=template0;
EOF


coloredEcho "Database creation complete!" "yellow"

# Tag the provision time:
date > "$PROVISIONED_ON"

coloredEcho "Installing global python packages" "cyan"
pip3 install poetry

print_db_usage
echo ""
coloredEcho "Successfully created {{cookiecutter.project_name}} dev virtual machine." "blue"
