#!/usr/bin/env bash
# Based on script from https://github.com/jackdb/pg-app-dev-vm/blob/master/Vagrant-setup/bootstrap.sh

set -e

curl https://raw.githubusercontent.com/IgnisDa/printr/main/get-printr.sh | sh -s -- --yes

export DEBIAN_FRONTEND=noninteractive

PROVISIONED_ON=/etc/vm_provision_on_timestamp
if [ -f "$PROVISIONED_ON" ]
then
  echo "VM was already provisioned at: $(cat $PROVISIONED_ON)"
  echo "To run system updates manually login via 'vagrant ssh' and run 'apt-get update"
  echo ""
  exit
fi

printr -c cyan -f bold "Adding apt-keys and installing environment packages"

# Get installer for nodejs
curl -sL https://deb.nodesource.com/setup_15.x | bash -
# get installer for yarn
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
# Update package list
apt-get update
curl -fsSL https://get.docker.com | sh
sudo usermod -aG docker vagrant

# Install postgresql, python3.9 and fish shell (required for development)
apt-get -y install "yarn" "bat" "fish" "python3" "python3-pip" "nodejs" "gcc" "g++" "make" "exa" "neovim" "build-essential" "python"

printr -c yellow -f bold "Environment packages installed successfully!"

echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
sudo sysctl -p

# Tag the provision time:
date > "$PROVISIONED_ON"
timedatectl set-ntp true
timedatectl set-timezone Asia/Kolkata

echo ""
printr -c blue -f bold "Successfully created {{cookiecutter.project_name}} development virtual machine"
