#!/usr/bin/env bash
# This script will be used to install dependencies for all the {{cookiecutter.project_name}} applications

# setup the git identities
git config --global user.name "{{cookiecutter.github_username}}"
git config --global user.email "{{cookiecutter.github_email}}"

# remove the default fish shell prompt
set fish_greeting

# install Gitzer to the system
curl -sSL https://raw.githubusercontent.com/IgnisDa/Gitzer/main/get-gitzer.py | python3

# replace the default file content viewer (cat) with bat
mkdir -p $HOME/.local/bin
ln -s /usr/bin/batcat $HOME/.local/bin/bat
mkdir -p $HOME/.config/fish/
echo "alias cat=\"batcat\"" >> $HOME/.config/fish/config.fish

# use the starship prompt
curl -fsSL https://starship.rs/install.sh > /tmp/install.sh
chmod +x /tmp/install.sh
/tmp/install.sh --force
echo "which starship &>/dev/null && starship init fish | source" >> $HOME/.config/fish/config.fish
curl -sSL https://raw.githubusercontent.com/IgnisDa/linux-configs/master/starship.toml > $HOME/.config/starship.toml

# set the default interactive shell as fish
echo "if [[ \$(ps --no-header --pid=\$PPID --format=cmd) != \"fish\" ]]" >> $HOME/.bashrc
echo "then" >> $HOME/.bashrc
echo "   exec fish" >> $HOME/.bashrc
echo "fi" >> $HOME/.bashrc

# change to the project folder
cd "/home/vagrant/{{cookiecutter.project_name}}"
# install the dependencies for the frontend application
yarn
