#!/usr/bin/env bash
# This script will be used to install dependencies for all the {{cookiecutter.project_name}} applications

# setup the git identities
git config --global user.name "{{cookiecutter.github_name}}"
git config --global user.email "{{cookiecutter.github_email}}"

# remove the default fish shell prompt
set fish_greeting

# install Gitzer to the system
curl -sSL https://raw.githubusercontent.com/IgnisDa/Gitzer/main/get-gitzer.py | python3

# replace the default file content viewer (cat) with bat
sudo ln -s /usr/bin/batcat /usr/bin/bat
# load all my system configs
rm -rf $HOME/.config
git clone https://github.com/IgnisDa/linux-configs.git $HOME/.config

# load all the custom scripts
CUSTOM_SCRIPTS_DIR="$HOME/custom-scripts"
git clone https://github.com/IgnisDa/custom-scripts.git $CUSTOM_SCRIPTS_DIR
chmod +x $CUSTOM_SCRIPTS_DIR/build
chmod +x $CUSTOM_SCRIPTS_DIR/run
chmod +x $CUSTOM_SCRIPTS_DIR/setup

# use the starship prompt
curl -fsSL https://starship.rs/install.sh > /tmp/install.sh
chmod +x /tmp/install.sh
/tmp/install.sh --force

# rust installer
curl https://sh.rustup.rs -sSf | sh -s -- -y

# set the default interactive shell as fish
echo "if [[ \$(ps --no-header --pid=\$PPID --format=cmd) != \"fish\" ]]" >> $HOME/.bashrc
echo "then" >> $HOME/.bashrc
echo "   exec fish" >> $HOME/.bashrc
echo "fi" >> $HOME/.bashrc

# change to the project folder
cd "$HOME/{{cookiecutter.project_name}}"

# we prefer not to keep the virtual environment as a part of the synced directory for
# performance reasons, hence we create a folder to store all of them and use symbolic links
# for the project purposes
# first we create a directory where our custom scripts are stored
"$CUSTOM_SCRIPTS_DIR/setup"
