#!/usr/bin/env bash
# This script will be used to install dependencies for all the {{cookiecutter.project_name}} applications

# setup the git identities
git config --global user.name "{{cookiecutter.github_username}}"
git config --global user.email "{{cookiecutter.github_email}}"

# remove the default fish shell prompt
set fish_greeting

# install Gitzer to the system
curl -sSL https://raw.githubusercontent.com/IgnisDa/Gitzer/main/get-gitzer.py | python3

# replace the default file content viewer (cat) with bat
sudo ln -s /usr/bin/batcat /usr/bin/bat

# load all my system configs
rm -rf $HOME/.config
git clone https://github.com/IgnisDa/linux-configs.git $HOME/.config

# use the starship prompt
curl -fsSL https://starship.rs/install.sh > /tmp/install.sh
chmod +x /tmp/install.sh
/tmp/install.sh --force

# set the default interactive shell as fish
echo "if [[ \$(ps --no-header --pid=\$PPID --format=cmd) != \"fish\" ]]" >> $HOME/.bashrc
echo "then" >> $HOME/.bashrc
echo "   exec fish" >> $HOME/.bashrc
echo "fi" >> $HOME/.bashrc

# change to the project folder
cd "/home/vagrant/{{cookiecutter.project_name}}"
# install the dependencies for the frontend application
yarn

# we prefer not to keep the virtual environment as a part of the synced directory for
# performance reasons, hence we create a folder to store all of them and use symbolic links
# for the project purposes
cache_folder="$HOME/.project-cache/{{cookiecutter.project_name}}"
frontend_cache="$cache_folder/$frontend_folder"

mkdir -p "$frontend_cache"

# for the frontend project folder
mv "$HOME/{{cookiecutter.project_name}}/$frontend_folder/node_modules" "$frontend_cache/node_modules"
ln -s "$frontend_cache/node_modules" "$HOME/{{cookiecutter.project_name}}/$frontend_folder/node_modules"
